//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Errors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Errors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DataModel.Resources.Errors", typeof(Errors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer already exists..
        /// </summary>
        public static string AlreadyExist {
            get {
                return ResourceManager.GetString("AlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Context not set..
        /// </summary>
        public static string ContextNotSet {
            get {
                return ResourceManager.GetString("ContextNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An email address is required..
        /// </summary>
        public static string Customer_EmailIsRequired {
            get {
                return ResourceManager.GetString("Customer_EmailIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer was not deleted..
        /// </summary>
        public static string Customer_NotDeleted {
            get {
                return ResourceManager.GetString("Customer_NotDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The customer is not found or doesn&apos;t exist..
        /// </summary>
        public static string Customer_NotFound {
            get {
                return ResourceManager.GetString("Customer_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The customer needs to be set..
        /// </summary>
        public static string Customer_NotSet {
            get {
                return ResourceManager.GetString("Customer_NotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password needs to be set..
        /// </summary>
        public static string Customer_Password {
            get {
                return ResourceManager.GetString("Customer_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting by id is not supported..
        /// </summary>
        public static string DeletingById {
            get {
                return ResourceManager.GetString("DeletingById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The description is required..
        /// </summary>
        public static string DescriptionIsRequired {
            get {
                return ResourceManager.GetString("DescriptionIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The description needs to be at least 5 chars..
        /// </summary>
        public static string DescriptionIsToShort {
            get {
                return ResourceManager.GetString("DescriptionIsToShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The description need to be no more than 800 chars..
        /// </summary>
        public static string DescriptionsIsToLong {
            get {
                return ResourceManager.GetString("DescriptionsIsToLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email or password is incorrect..
        /// </summary>
        public static string EmailOrPassword {
            get {
                return ResourceManager.GetString("EmailOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exercise was not deleted..
        /// </summary>
        public static string Exercise_NotDeleted {
            get {
                return ResourceManager.GetString("Exercise_NotDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An exercise is not found or doesn&apos;t exist..
        /// </summary>
        public static string Exercise_NotFound {
            get {
                return ResourceManager.GetString("Exercise_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Field needs to be set..
        /// </summary>
        public static string FieldIsRequired {
            get {
                return ResourceManager.GetString("FieldIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Field need to be no more than 50 chars..
        /// </summary>
        public static string FieldIsToLong {
            get {
                return ResourceManager.GetString("FieldIsToLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Field need to be at least 4 chars..
        /// </summary>
        public static string FieldIsToShort {
            get {
                return ResourceManager.GetString("FieldIsToShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something has gone wrong. Please try again later..
        /// </summary>
        public static string InternalException {
            get {
                return ResourceManager.GetString("InternalException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid request..
        /// </summary>
        public static string InvalidRequest {
            get {
                return ResourceManager.GetString("InvalidRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value was not saved..
        /// </summary>
        public static string NotSaved {
            get {
                return ResourceManager.GetString("NotSaved", resourceCulture);
            }
        }
    }
}
