//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Errors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Errors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DataModel.Resources.Errors", typeof(Errors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting by id is not supported..
        /// </summary>
        public static string DeletingById {
            get {
                return ResourceManager.GetString("DeletingById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The description is required..
        /// </summary>
        public static string DescriptionIsRequired {
            get {
                return ResourceManager.GetString("DescriptionIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The description needs to be at least 5 chars..
        /// </summary>
        public static string DescriptionIsToShort {
            get {
                return ResourceManager.GetString("DescriptionIsToShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The description need to be no more than 800 chars..
        /// </summary>
        public static string DescriptionsIsToLong {
            get {
                return ResourceManager.GetString("DescriptionsIsToLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Given Element did not exists..
        /// </summary>
        public static string ElementNotExists {
            get {
                return ResourceManager.GetString("ElementNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email or password is incorrect..
        /// </summary>
        public static string EmailOrPassword {
            get {
                return ResourceManager.GetString("EmailOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Field needs to be set..
        /// </summary>
        public static string FieldIsRequired {
            get {
                return ResourceManager.GetString("FieldIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Field need to be no more than 50 chars..
        /// </summary>
        public static string FieldIsToLong {
            get {
                return ResourceManager.GetString("FieldIsToLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Field need to be at least 4 chars..
        /// </summary>
        public static string FieldIsToShort {
            get {
                return ResourceManager.GetString("FieldIsToShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong. Please try again later..
        /// </summary>
        public static string InternalException {
            get {
                return ResourceManager.GetString("InternalException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid request..
        /// </summary>
        public static string InvalidRequest {
            get {
                return ResourceManager.GetString("InvalidRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid request. Primary key ist not set..
        /// </summary>
        public static string InvalidRequest_PrimaryKeyNotSet {
            get {
                return ResourceManager.GetString("InvalidRequest_PrimaryKeyNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid request. Entity to create contained Pk..
        /// </summary>
        public static string InvalidRequest_PrimaryKeySet {
            get {
                return ResourceManager.GetString("InvalidRequest_PrimaryKeySet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not found..
        /// </summary>
        public static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value was not saved..
        /// </summary>
        public static string NotSaved {
            get {
                return ResourceManager.GetString("NotSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object is null..
        /// </summary>
        public static string NullObject {
            get {
                return ResourceManager.GetString("NullObject", resourceCulture);
            }
        }
    }
}
